### PR TITLE
Support test kitchen < 4 version

### PR DESCRIPTION
**Pull request by Svedrin**
supersedes https://github.com/Proemion/kitchen-transport-rsync/pull/1

### CODE REVIEW

**Comment by mfuhrmann** [comment]
@Svedrin I think I can just merge this one to try the Kitchen/Gem magic part in real, right?
I know it works with `https://github.com/coupa-ops/kitchen-transport-rsync`.

**Comment by Svedrin** [comment]
@mfuhrmann yep, I think so

**Comment by mfuhrmann** [comment]
Ok. Then let's merge and let me test it.

**Comment by mfuhrmann** [comment]
I've tested it like this:
`gem 'kitchen-transport-rsync', git: "https://github.com/Proemion/kitchen-transport-rsync", branch: "0-update-from-coupa-ops"`
which worked perfectly. So merging won't cause a problem I think.

**Pull request merged**
